//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SetCaretBackGroundColor.rc
//
#define WM_USER_NTFYICON                101
#define IDD_SETCARETBACKGROUNDCOLOR_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDI_TRAYICON                    129
#define IDR_TRAYMENU                    130
#define IDD_CONFIGDIALOG                131
#define IDD_DIALOG_IGNORE               132
#define IDC_SLIDER_TRANSPARENT          1000
#define IDC_SLIDER_TRANSPARENT_OPEN     1000
#define IDC_SLIDER_TRANSPARENT_CLOSE    1001
#define IDC_BUTTON_COLOR_OPEN           1003
#define IDC_BUTTON_COLOR_CLOSE          1004
#define IDC_SLIDER_BLINK_COUNT          1006
#define IDC_SLIDER_BLINK_FADE_LENGTH    1007
#define IDC_STATIC_PICTURE_COLOR_OPEN   1008
#define IDC_STATIC_PICTURE_COLOR_CLOSE  1009
#define IDC_EDIT_BLINK_FRAMELENGTH      1010
#define IDC_EDIT_BLINK_COUNT            1011
#define IDC_LIST_IGNORE_CLASSNAME       1011
#define IDC_EDIT_COLOR_OPEN             1012
#define IDC_BUTTON_CLASSNAME_ADD        1012
#define IDC_EDIT_COLOR_CLOSE            1013
#define IDC_EDIT_IGNORE_CLASSNAME       1013
#define IDC_LIST_IGNORE_CLASSNAME_HISTORY 1014
#define IDC_BUTTON_CLASSNAME_REMOVE     1015
#define IDC_BUTTON_CLOSE                1015
#define IDC_BUTTON_CONFIG_CLOSE         1015
#define IDC_BUTTON_IGNORE_CLOSE         1017
#define IDC_HOTKEY_CONFIG_MANUAL_BLINK  1018
#define IDC_BUTTON_CONFIG_MANUAL_BLINK_SET 1019
#define ID_MENUITEM_TRAY_EXIT           32773
#define ID_MENUITEM_TRANSPARENT         32775
#define ID_MENUITEM_TRAY_CANCEL         32777
#define ID_MENUITEM_TRAY_CONFIG         32778
#define ID_MENUITEM_TRAY_RESTART        32780
#define ID_MENUITEM_TRAY_IGNORE         32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
